[build]
  publish = "storybook-static"
  command = "npm run build-storybook"

[build.environment]
  NODE_VERSION = "18"

# Headers for security - allowing frames for Storybook
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirect rules
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 