/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.{js,ts,jsx,tsx,mdx}',
    './stories/**/*.{js,ts,jsx,tsx,mdx}',
    './.storybook/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        title: ['var(--vromm-font-family-title)'],
        sans: ['var(--vromm-font-family-sans)'],
        mono: ['var(--vromm-font-family-mono)'],
      },
      colors: {
        // Standard Tailwind colors needed for @apply directives in our SCSS
        white: '#ffffff',
        black: '#000000',
        transparent: 'transparent',
        current: 'currentColor',
        gray: {
          50: '#f9fafb',
          100: '#f3f4f6',
          200: '#e5e7eb',
          300: '#d1d5db',
          400: '#9ca3af',
          500: '#6b7280',
          600: '#4b5563',
          700: '#374151',
          800: '#1f2937',
          900: '#111827',
        },
        blue: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
        },
        red: {
          50: '#fef2f2',
          100: '#fee2e2',
          200: '#fecaca',
          300: '#fca5a5',
          400: '#f87171',
          500: '#ef4444',
          600: '#dc2626',
          700: '#b91c1c',
          800: '#991b1b',
          900: '#7f1d1d',
        },
        green: {
          50: '#f0fdf4',
          100: '#dcfce7',
          200: '#bbf7d0',
          300: '#86efac',
          400: '#4ade80',
          500: '#22c55e',
          600: '#16a34a',
          700: '#15803d',
          800: '#166534',
          900: '#14532d',
        },
        yellow: {
          50: '#fefce8',
          100: '#fef3c7',
          200: '#fde68a',
          300: '#fcd34d',
          400: '#fbbf24',
          500: '#f59e0b',
          600: '#d97706',
          700: '#b45309',
          800: '#92400e',
          900: '#78350f',
        },
        
        // Our custom brand colors using CSS custom properties
        primary: {
          50: 'var(--vromm-color-primary-50)',
          100: 'var(--vromm-color-primary-100)',
          200: 'var(--vromm-color-primary-200)',
          300: 'var(--vromm-color-primary-300)',
          400: 'var(--vromm-color-primary-400)',
          500: 'var(--vromm-color-primary-500)',
          600: 'var(--vromm-color-primary-600)',
          700: 'var(--vromm-color-primary-700)',
          800: 'var(--vromm-color-primary-800)',
          900: 'var(--vromm-color-primary-900)',
        },
        // Secondary colors
        secondary: {
          50: 'var(--vromm-color-secondary-50)',
          100: 'var(--vromm-color-secondary-100)',
          200: 'var(--vromm-color-secondary-200)',
          300: 'var(--vromm-color-secondary-300)',
          400: 'var(--vromm-color-secondary-400)',
          500: 'var(--vromm-color-secondary-500)',
          600: 'var(--vromm-color-secondary-600)',
          700: 'var(--vromm-color-secondary-700)',
          800: 'var(--vromm-color-secondary-800)',
          900: 'var(--vromm-color-secondary-900)',
        },
        // Neutral colors
        neutral: {
          50: 'var(--vromm-color-neutral-50)',
          100: 'var(--vromm-color-neutral-100)',
          200: 'var(--vromm-color-neutral-200)',
          300: 'var(--vromm-color-neutral-300)',
          400: 'var(--vromm-color-neutral-400)',
          500: 'var(--vromm-color-neutral-500)',
          600: 'var(--vromm-color-neutral-600)',
          700: 'var(--vromm-color-neutral-700)',
          800: 'var(--vromm-color-neutral-800)',
          900: 'var(--vromm-color-neutral-900)',
        },
        // Semantic colors
        success: {
          50: 'var(--vromm-color-success-50)',
          100: 'var(--vromm-color-success-100)',
          200: 'var(--vromm-color-success-200)',
          300: 'var(--vromm-color-success-300)',
          400: 'var(--vromm-color-success-400)',
          500: 'var(--vromm-color-success-500)',
          600: 'var(--vromm-color-success-600)',
          700: 'var(--vromm-color-success-700)',
          800: 'var(--vromm-color-success-800)',
          900: 'var(--vromm-color-success-900)',
        },
        warning: {
          50: 'var(--vromm-color-warning-50)',
          100: 'var(--vromm-color-warning-100)',
          200: 'var(--vromm-color-warning-200)',
          300: 'var(--vromm-color-warning-300)',
          400: 'var(--vromm-color-warning-400)',
          500: 'var(--vromm-color-warning-500)',
          600: 'var(--vromm-color-warning-600)',
          700: 'var(--vromm-color-warning-700)',
          800: 'var(--vromm-color-warning-800)',
          900: 'var(--vromm-color-warning-900)',
        },
        error: {
          50: 'var(--vromm-color-error-50)',
          100: 'var(--vromm-color-error-100)',
          200: 'var(--vromm-color-error-200)',
          300: 'var(--vromm-color-error-300)',
          400: 'var(--vromm-color-error-400)',
          500: 'var(--vromm-color-error-500)',
          600: 'var(--vromm-color-error-600)',
          700: 'var(--vromm-color-error-700)',
          800: 'var(--vromm-color-error-800)',
          900: 'var(--vromm-color-error-900)',
        },
        
        // Button semantic colors for easy usage
        'button-primary': {
          DEFAULT: 'var(--vromm-button-primary-bg)',
          hover: 'var(--vromm-button-primary-hover)', 
          text: 'var(--vromm-button-primary-text)',
          border: 'var(--vromm-button-primary-border)',
        },
        'button-secondary': {
          DEFAULT: 'var(--vromm-button-secondary-bg)',
          hover: 'var(--vromm-button-secondary-hover)',
          text: 'var(--vromm-button-secondary-text)', 
          border: 'var(--vromm-button-secondary-border)',
        },
        'button-tertiary': {
          DEFAULT: 'var(--vromm-button-tertiary-bg)',
          hover: 'var(--vromm-button-tertiary-hover)',
          text: 'var(--vromm-button-tertiary-text)',
          border: 'var(--vromm-button-tertiary-border)',
        },
        
        // Brand text colors
        'page-title': 'var(--vromm-color-page-title)',
        'body-text': 'var(--vromm-color-text)',
        
        // Semantic color aliases
        background: 'var(--vromm-color-background)',
        foreground: 'var(--vromm-color-text)',
        border: 'var(--vromm-color-border)',
        muted: {
          DEFAULT: 'var(--vromm-color-background-medium)',
          foreground: 'var(--vromm-color-text-weak)',
        },
        accent: {
          DEFAULT: 'var(--vromm-color-background-strong)',
          foreground: 'var(--vromm-color-text)',
        },
        destructive: {
          DEFAULT: 'var(--vromm-color-error-500)',
          foreground: 'var(--vromm-color-text-inverted)',
        },
      },
      spacing: {
        xs: 'var(--vromm-spacing-xs)',
        sm: 'var(--vromm-spacing-sm)',
        md: 'var(--vromm-spacing-md)',
        lg: 'var(--vromm-spacing-lg)',
        xl: 'var(--vromm-spacing-xl)',
        '2xl': 'var(--vromm-spacing-2xl)',
      },
      borderRadius: {
        'vromm-sm': 'var(--vromm-radius-sm)',
        'vromm-md': 'var(--vromm-radius-md)',
        'vromm-lg': 'var(--vromm-radius-lg)',
        'vromm-xl': 'var(--vromm-radius-xl)',
        'brand': 'var(--vromm-radius-brand)', // 12px brand radius
      },
      fontSize: {
        'text-xs': ['0.75rem', { lineHeight: '1rem' }],
        'text-sm': ['0.875rem', { lineHeight: '1.25rem' }],
        'text-base': ['1rem', { lineHeight: '1.5rem' }],
        'text-lg': ['1.125rem', { lineHeight: '1.75rem' }],
        'text-xl': ['1.25rem', { lineHeight: '1.75rem' }],
        'text-2xl': ['1.5rem', { lineHeight: '2rem' }],
        'text-3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        'text-4xl': ['2.25rem', { lineHeight: '2.5rem' }],
        'text-5xl': ['3rem', { lineHeight: '1' }],
        'text-6xl': ['3.75rem', { lineHeight: '1' }],
      },
      fontWeight: {
        'brand': '600', // Brand font weight
      },
      keyframes: {
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'slide-in': {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
      },
      animation: {
        'fade-in': 'fade-in 0.3s ease-in-out',
        'slide-in': 'slide-in 0.3s ease-in-out',
      },
    },
  },
  plugins: [],
}; 